version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  test: # this can be any name you want
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run sample-test
          name: Run tests

      - store_artifacts:
          path: /home/circleci/project/reports/report.html
          destination: browserstack-reports

      - persist_to_workspace:
          root: ~/project
          paths:
            - .


workflows:
  adobe-pr-smoke-test:
    jobs:
      - test