version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  percy: percy/agent@volatile

jobs:
  test: # this can be any name you want
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run sample-test
          name: Run tests
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts

      - persist_to_workspace:
          root: ~/project
          paths:
            - .
      - store_test_results:
          path: results.xml


workflows:
  adobe-pr-smoke-test:
    jobs:
      - test
      - percy/finalize_all:
         requires:
           - test

