version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  slack: circleci/slack@4.12.5

jobs:
  test: # this can be any name you want
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run sample-test
          name: Run tests

      - store_artifacts:
          path: /home/circleci/project/reports/report.html
          destination: browserstack-reports

      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  notify:
    steps:
      - slack/notify:
        custom: |
          {
            "blocks": [
              {
                "type": "section",
                "fields": [
                  {
                    "type": "plain_text",
                    "text": "*This is a text notification*",
                    "emoji": true
                  }
                ]
              }
            ]
          }
        event: always
workflows:
  adobe-pr-smoke-test:
    jobs:
      - test
  
  send-notification:
    jobs:
      - notify:
          context: slack-secrets
